default_context:
  project_name: 'Steam Site'
  project_slug: 'steam-site'
  domain_main: 'steam-site.matthiggins.app'
  domain_staging: 'stag.steam-site.matthiggins.app'
  docker_swarm_stack_name_main: 'steam-site-matthiggins-app'
  docker_swarm_stack_name_staging: 'stag-steam-site-matthiggins-app'
  secret_key: 'a14975906b202d1d045f2371ef9dde618995ab90e70ef2a4bec6906086e1ac31'
  first_superuser: 'matt@matthiggins.dev'
  first_superuser_password: 'horsebattery'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.steam-site.matthiggins.app", "https://stag.steam-site.matthiggins.app", "https://steam-site.matthiggins.app", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@steam-site.matthiggins.app'
  postgres_password: 'horsebattery'
  pgadmin_default_user: 'matt@matthiggins.dev'
  pgadmin_default_user_password: 'horsebattery'
  traefik_constraint_tag: 'steam-site.matthiggins.app'
  traefik_constraint_tag_staging: 'stag.steam-site.matthiggins.app'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:horsebattery'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
